### PR TITLE
Use 'tox' on Travis.

### PR DESCRIPTION
**Pull request by tseaver**
Get 'coverage' and 'docs' tested there too.

### CODE REVIEW

**Comment by jamadden** [comment]
You beat me too it!

**Comment by jamadden** [comment]
Do you intend to work on fixing the doctests, disable them, or would you like me to fix them (since I did break them)?

**Comment by tseaver** [comment]
I haven't looked at what it will take to fix them, and probably can't today.

**Comment by jamadden** [comment]
I can fix them. It won't take much. I currently have a branch based off this branch where i'm fixing them. I can finish fixing them there and open a PR for that, if that's OK.

**Pull request merged**
