### PR TITLE
Keep Sphinx doc version in sync with release version.

### PR DESCRIPTION
**Pull request by jamadden**
Using a version.txt file. This works with zest.releaser.

As mentioned in #24.

### CODE REVIEW

**Comment by mgedmin** [comment]
LGTM

**Comment by jamadden** [comment]
Thanks for all the quick reviews!

**Comment by mgedmin** [comment]
Not only quick, but also very superficial! ;)

**Comment by jamadden** [comment]
That's alright, I trust me 😉

**Pull request merged**
