### PR TITLE
Test docs and coverage on travis using tox; fix doctests

### PR DESCRIPTION
**Pull request by jamadden**
Supersedes #26.

### CODE REVIEW

**Comment by jamadden** [comment]
Travis is green!

I apologize for the breakage. I guess that's what I deserve for [being smart](https://github.com/zopefoundation/zope.schema/pull/25#issuecomment-247097154).

**Comment by mgedmin** [comment]
BTW are the u/b compat helpers used anywhere else?  Time to remove them perhaps?

**Comment by jamadden** [comment]
TBH in return, I don't know what doctests are supposed to see, and exactly how that varies among the stdlib `doctest` module and the Sphinx implementation. I just did what was necessary to make sphinx pass, which was all that seemed to be testing these snippets.

Given a signoff, then with more humility this time I am going to go ahead and merge this PR for the sake of fixing tox doctests. Please let me know if I this breaks anything else or if I can improve it in any way.

**Comment by jamadden** [comment]
> BTW are the u/b compat helpers used anywhere else? Time to remove them perhaps?

At least the `u` helper is used in keyword argument defaults, but it should no longer be necessary. It can be removed, I think, but that's another PR. I had some one-off scripts to do that for [zope.interface](https://github.com/zopefoundation/zope.interface/pull/43) that probably wouldn't be that hard to recreate for this package.

**Pull request merged**
