### PR TITLE
Drop support for Python < 3.7

### PR DESCRIPTION
**Pull request by cjwatson**
https://github.com/zopefoundation/zope.testing/pull/45 broke zope.schema's tests, so I guess it's time to do the corresponding removal here as well.

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for (reviewing) this PR. 😃

**Comment by cjwatson** [comment]
Would anyone be willing to either release this to PyPI, or give me access so I can do it myself?

**Comment by mgedmin** [comment]
Released!

(I don't mind giving you PyPI access, but please mention your PyPI username in your request, as I'd hate to guess and get it wrong.)

**Comment by jugmac00** [comment]
Colin on PyPI
https://pypi.org/user/cjwatson/
(He's my colleague at work).

**Comment by cjwatson** [comment]
What Jürgen said.  This would probably still be useful for future releases.  (Thanks for doing 7.0.0.)

**Pull request merged**
