### PR TITLE
Point to https://zopeschema.readthedocs.io/ instead of docs.zope.org

### LINKED ISSUE #21: http://docs.zope.org/zope.schema/ outdated
http://docs.zope.org/zope.schema/ is for zope.schema 4.2, and this is quite problematic as http://docs.zope.org/zope.schema/hacking.html#getting-the-code points to the SVN repo instead of github.

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #21.

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks! Maybe it's time for a release, in order to publish a wheel and update the URL? I'd be happy to if I had access.

**Comment by tseaver** [comment]
@jamadden I just added you as an owner on PyPI.

**Comment by tseaver** [comment]
...and I don't think another release is premature:  just modernizing the set of supported Pythons is enough for one, IMHO.

**Comment by jamadden** [comment]
Thanks! 4.5.0 has been uploaded to PyPI.

**Pull request merged**
